# Executed from build-pages.py after book pages exist. Adds "Về cuốn sách" card (level, audience, topics, where to start). Draft, AI-assisted, not pastor-reviewed.
_BI = {
 "bavinck-revelation": (3, "Sinh viên thần học, người quen đọc triết học", "Mặc khải, nhận thức, thần học nền tảng", "Hãy đọc Reformed Dogmatics hoặc một tóm lược trước nếu bạn mới."),
 "baxter-causes": (2, "Người muốn tự xét lòng mình", "Xem thường Tin Lành, ăn năn", "Đọc từng chương ngắn, mỗi ngày một chương."),
 "baxter-pastor": (2, "Mục sư và người hầu việc Chúa", "Chức vụ mục sư, chăm sóc con chiên", "Bắt đầu với phần lời kêu gọi mục sư tự xét mình."),
 "baxter-practical": (3, "Người đọc nhiều, muốn tra cứu", "Mục vụ, đời sống đạo, Thanh giáo", "Đây là tuyển tập lớn; hãy chọn từng bài thay vì đọc từ đầu."),
 "baxter-saints-rest": (2, "Tín hữu đang mệt mỏi hoặc đau yếu", "Thiên đàng, sự trông cậy", "Đọc phần mở đầu về sự yên nghỉ đời đời trước."),
 "baxter-unconverted": (1, "Người chưa tin, người muốn truyền giảng", "Phúc Âm, ăn năn", "Một lời kêu gọi ngắn, có thể đọc trong một lần."),
 "berkhof-summary": (2, "Người mới học giáo lý Cải Chánh", "Giáo lý tổng quát", "Đọc theo thứ tự các chương; ngắn hơn bộ Systematic Theology."),
 "berkhof-systematictheology": (3, "Sinh viên thần học, mục sư", "Thần học hệ thống Cải Chánh", "Dùng như sách tra cứu theo chủ đề."),
 "boettner-predest": (3, "Người muốn hiểu sâu giáo lý tiền định", "Tiền định, chọn lựa, chủ quyền Đức Chúa Trời", "Đọc cùng Kinh Thánh (Rô-ma 9, Ê-phê-sô 1) và hỏi mục sư."),
 "bonar-peace": (1, "Người đang tìm bình an với Đức Chúa Trời", "Phúc Âm, bình an, ân điển", "Sách ngắn, hợp cho người mới."),
 "boston-crook": (2, "Người đang chịu hoạn nạn", "Nghịch cảnh, chủ quyền Đức Chúa Trời", "Đọc khi gặp thử thách."),
 "boyce-theology": (3, "Sinh viên thần học Báp-tít", "Thần học hệ thống Báp-tít", "Dùng như sách tra cứu."),
 "bunyan-badman": (2, "Người thích truyện ngụ ngôn, đối thoại", "Lòng chai đá, sự phán xét", "Đọc như một câu chuyện cảnh tỉnh."),
 "bunyan-grace": (2, "Người từng vật lộn với tội lỗi và nghi ngờ", "Ân điển, tội lỗi, đức tin", "Đọc như một tự truyện thuộc linh."),
 "bunyan-holy-war": (2, "Người thích truyện ngụ ngôn", "Chiến trận thuộc linh", "Đọc sau The Pilgrim's Progress."),
 "bunyan-miscellaneous": (2, "Người muốn đọc thêm Bunyan", "Đời sống Cơ Đốc", "Chọn từng bài ngắn."),
 "bunyan-pilgrim": (1, "Mọi người, kể cả người mới tin", "Hành trình đức tin, sự cứu rỗi", "Đọc phần một trước; có thể đọc cùng gia đình."),
 "calvin-chr-life": (2, "Người muốn sống đức tin nghiêm túc", "Từ bỏ mình, thập tự giá, đời sau", "Đọc từng đoạn ngắn, mỗi ngày một đoạn."),
 "calvin-institutes": (3, "Người muốn học nền tảng giáo lý Cải Chánh", "Toàn bộ giáo lý Cải Chánh", "Đọc quyển III về ân điển trước, hoặc dùng làm sách tra cứu."),
 "calvin-prayer": (2, "Người muốn học cầu nguyện theo Kinh Thánh", "Cầu nguyện, đức tin", "Một chương, đọc trong một hai lần."),
 "calvin-sermons": (3, "Người muốn thấy cách Calvin giảng Kinh Thánh", "Giảng giải Kinh Thánh", "Chọn một bài về sách bạn đang đọc."),
 "charnock-nat-regen": (3, "Người đọc nhiều sách Thanh giáo", "Tái sanh, công việc của Thánh Linh", "Đọc cùng Giăng 3."),
 "charnock-nec-regen": (3, "Người đọc nhiều sách Thanh giáo", "Tái sanh", "Đọc sau bài về bản chất của sự tái sanh."),
 "doddridge-rise": (2, "Người muốn lớn lên từ khi mới tin", "Tăng trưởng thuộc linh, đức tin", "Đọc theo thứ tự các chương."),
 "edwards-affections": (3, "Người muốn thử xem đức tin mình có thật không", "Cảm xúc thuộc linh, sự thật và giả", "Bắt đầu với phần dấu hiệu của cảm xúc thật."),
 "edwards-sermons": (2, "Người thích bài giảng cổ điển", "Giảng đạo, Phục hưng", "Đọc 'Sinners in the Hands of an Angry God' trước."),
 "edwards-will": (3, "Sinh viên thần học", "Ý chí, chủ quyền Đức Chúa Trời", "Cần đọc chậm và nhiều lần."),
 "flavel-fountain": (2, "Người muốn biết Đấng Christ sâu hơn", "Thân vị và công việc Đấng Christ", "Chọn từng bài giảng."),
 "flavel-grace": (2, "Người muốn hiểu sự cứu chuộc được áp dụng thế nào", "Sự cứu rỗi, ân điển", "Đọc theo thứ tự."),
 "flavel-life": (1, "Người thích đọc tiểu sử", "Tiểu sử Thanh giáo", "Ngắn, đọc trong một lần."),
 "flavel-lovely": (2, "Người muốn yêu Đấng Christ hơn", "Vẻ đẹp của Đấng Christ, Nhã-ca 5", "Đọc từng bài suy niệm."),
 "flavel-saintindeed": (2, "Người muốn giữ lòng mình", "Giữ lòng, đời sống thuộc linh", "Đọc chậm, mỗi ngày một đoạn."),
 "gill-doctrinal": (3, "Mục sư, sinh viên thần học Báp-tít", "Thần học hệ thống", "Dùng như sách tra cứu."),
 "gill-practical": (3, "Mục sư, sinh viên thần học Báp-tít", "Đời sống và bổn phận Cơ Đốc", "Dùng như sách tra cứu."),
 "henry-mhcc": (1, "Mọi người học Kinh Thánh", "Chú giải Kinh Thánh", "Đọc cùng đoạn Kinh Thánh bạn đang học."),
 "hodge-darwinism": (3, "Người quan tâm khoa học và đức tin", "Nguồn gốc, thuyết tiến hóa", "Lưu ý đây là tranh luận thế kỷ XIX."),
 "hodge-ephesians": (3, "Người học thư Ê-phê-sô nghiêm túc", "Chú giải thư Ê-phê-sô", "Đọc song song với thư Ê-phê-sô."),
 "hodge-theology1": (3, "Sinh viên thần học", "Thần học hệ thống, Kinh Thánh, Đức Chúa Trời", "Dùng như sách tra cứu."),
 "hooker-just": (3, "Người học lịch sử giáo lý xưng công bình", "Xưng công bình", "Đọc sau khi hiểu giáo lý cơ bản."),
 "knox-blast": (3, "Người học lịch sử Cải cách", "Chính trị thế kỷ XVI", "Cần đọc với bối cảnh lịch sử; nhiều người ngày nay không đồng ý nội dung."),
 "knox-history-reformation": (3, "Người học lịch sử Hội Thánh Scotland", "Lịch sử Cải cách ở Scotland", "Đọc như tài liệu lịch sử."),
 "knox-prayer": (2, "Người muốn học cầu nguyện", "Cầu nguyện", "Luận văn ngắn."),
 "kuyper-holy-spirit": (3, "Người muốn học về Đức Thánh Linh", "Đức Thánh Linh", "Đọc theo chủ đề bạn cần."),
 "kuyper-lecture": (3, "Người quan tâm đức tin và văn hóa", "Thuyết Calvin như một lối sống", "Sáu bài giảng; đọc mỗi bài riêng."),
 "kuyper-near": (2, "Người muốn suy niệm", "Gần Chúa, thờ phượng", "Mỗi bài ngắn, hợp để đọc mỗi ngày."),
 "owen-apostasy": (3, "Người đọc nhiều sách Thanh giáo", "Bội đạo, cảnh báo", "Đọc cùng thư Hê-bơ-rơ."),
 "owen-catechisms": (1, "Người mới, nhóm nhỏ, gia đình", "Giáo lý vấn đáp căn bản", "Rất ngắn, bắt đầu từ đây."),
 "owen-communion": (3, "Người muốn thông công sâu với Đức Chúa Trời", "Cha, Con, Thánh Linh, thông công", "Đọc chậm, từng phần."),
 "owen-conscience": (3, "Mục sư, người hướng dẫn", "Lương tâm, quyết định thực tế", "Chọn từng trường hợp."),
 "owen-deathofdeath": (3, "Sinh viên thần học", "Sự chuộc tội, giáo lý ân điển", "Đọc sau khi hiểu cơ bản về sự chuộc tội."),
 "owen-display": (3, "Người học lịch sử tranh luận Arminius", "Tranh luận Arminius", "Sách tranh luận, dành cho người đọc nhiều."),
 "owen-faith": (3, "Người muốn biết đức tin thật", "Đức tin cứu rỗi", "Đọc chậm."),
 "owen-glory": (3, "Người muốn chiêm ngưỡng Đấng Christ", "Vinh hiển Đấng Christ", "Mỗi chương là một suy niệm."),
 "owen-indwellingsin": (3, "Người đang chiến đấu với tội lỗi", "Tội lỗi còn trong người tin", "Đọc cùng Về sự làm chết tội lỗi."),
 "owen-just": (3, "Sinh viên thần học", "Xưng công bình", "Luận thuyết lớn; có thể đọc phần mở đầu trước."),
 "owen-justice": (3, "Sinh viên thần học", "Sự công chính của Đức Chúa Trời", "Dành cho người đọc nhiều."),
 "owen-mort": (2, "Người muốn thắng tội lỗi còn ở trong mình", "Chiến đấu với tội lỗi, nên thánh", "Một trong những điểm bắt đầu tốt nhất với Owen."),
 "owen-perseverance": (3, "Sinh viên thần học", "Sự bền đỗ của các thánh đồ", "Dành cho người đọc nhiều."),
 "owen-pneum": (3, "Sinh viên thần học", "Đức Thánh Linh", "Bộ lớn, đọc theo chủ đề."),
 "owen-psalm130": (2, "Người cần sự tha thứ và hy vọng", "Tha tội, hy vọng, Thi-thiên 130", "Hãy đọc kèm Thi-thiên 130."),
 "owen-sin-grace": (3, "Người đọc nhiều sách Thanh giáo", "Tội lỗi, ân điển, Rô-ma 6", "Đọc cùng Rô-ma 6."),
 "owen-spirituallyminded": (2, "Người muốn chuyên tâm vào điều thuộc linh", "Tâm trí thuộc linh, Rô-ma 8:6", "Đọc cùng Rô-ma 8."),
 "owen-temptation": (2, "Người đang bị cám dỗ", "Cám dỗ, tỉnh thức", "Sách ngắn, thực tế."),
 "owen-trinity": (3, "Sinh viên thần học", "Ba Ngôi", "Đọc ngắn nhưng cần suy nghĩ."),
 "owen-worship": (2, "Người muốn hiểu thờ phượng", "Thờ phượng", "Tài liệu ngắn."),
 "rutherford-letters": (1, "Người đang chịu khổ hoặc bị cô lập", "An ủi, tình yêu dành cho Đấng Christ", "Đọc từng thư, mỗi ngày một thư."),
 "rutherford-triumph": (3, "Người đọc nhiều sách Thanh giáo", "Đức tin bị thử thách", "Đọc chậm."),
 "ryle-holiness": (1, "Người mới và người lâu năm", "Nên thánh, chiến đấu thuộc linh", "Chương 'Sự thánh khiết' để bắt đầu."),
 "ryle-matthew": (1, "Người đọc Tin Lành Ma-thi-ơ", "Chú giải Tin Lành Ma-thi-ơ", "Đọc song song với từng đoạn Ma-thi-ơ."),
 "schaff-creeds1": (3, "Người học lịch sử giáo lý", "Lịch sử các tín điều", "Dùng để tra cứu."),
 "schaff-creeds3": (3, "Người muốn đọc nguyên văn các tín điều", "Westminster, Heidelberg", "Dùng để tra cứu."),
 "spurgeon-catechism": (1, "Gia đình, nhóm nhỏ, người mới", "Giáo lý vấn đáp", "Học thuộc từng câu hỏi."),
 "spurgeon-checkbook": (1, "Người muốn đọc mỗi ngày", "Lời hứa của Chúa, đức tin", "Mỗi ngày một trang ngắn."),
 "spurgeon-comment": (3, "Mục sư, người dạy Kinh Thánh", "Sách chú giải", "Dùng để chọn sách chú giải."),
 "spurgeon-grace": (1, "Người mới tin và người đang tìm hiểu", "Phúc Âm, ân điển", "Một trong những sách đầu tiên nên đọc."),
 "spurgeon-morneve": (1, "Mọi người", "Suy niệm hằng ngày", "Mỗi sáng và mỗi chiều một bài ngắn."),
 "spurgeon-treasury1": (2, "Người học Thi-thiên", "Chú giải Thi-thiên", "Đọc cùng Thi-thiên bạn đang suy gẫm."),
 "watson-beatitudes": (2, "Người học Bài giảng trên núi", "Chín phước, Ma-thi-ơ 5", "Đọc cùng Ma-thi-ơ 5."),
 "watson-commandments": (2, "Người học Mười điều răn", "Luật pháp, sự vâng phục", "Mỗi điều răn một phần."),
 "watson-contentment": (1, "Người đang lo lắng hoặc bất mãn", "Bằng lòng, Phi-líp 4:11", "Sách thực tế, hợp để đọc mỗi tuần một chương."),
 "watson-cordial": (1, "Người đang chịu hoạn nạn", "An ủi, hoạn nạn", "Sách ngắn."),
 "watson-divinity": (2, "Người muốn hiểu giáo lý Westminster", "Giáo lý căn bản", "Đọc từng phần theo câu hỏi."),
 "watson-prayer": (2, "Người muốn cầu nguyện theo Bài Cầu Nguyện Chúa Dạy", "Cầu nguyện", "Mỗi lời cầu xin một phần."),
}
_LV = {1: "Dễ đọc, hợp cho người mới", 2: "Trung bình, cần chú tâm", 3: "Sâu, dành cho người đã đọc nhiều"}
_bcss = '<style>.bi{margin:12px 0;padding:12px 14px;border-radius:10px;background:#8881}.bi dl{display:grid;grid-template-columns:auto 1fr;gap:4px 12px;margin:0;font-size:.92rem}.bi dt{opacity:.7}.bi dd{margin:0}.bi small{display:block;margin-top:8px;opacity:.7}</style>'
_n = 0
for _k, (_l, _w, _t, _s) in _BI.items():
    _p = f"b/{_k}.html"
    if not os.path.exists(_p): continue
    _h = open(_p, encoding="utf-8").read()
    if 'class="bi"' in _h: continue
    _card = (_bcss + f'<div class="bi"><dl><dt>Mức độ</dt><dd>{E(_LV[_l])}</dd><dt>Ai nên đọc</dt><dd>{E(_w)}</dd><dt>Chủ đề</dt><dd>{E(_t)}</dd><dt>Bắt đầu</dt><dd>{E(_s)}</dd></dl>'
             '<small>Gợi ý do AI soạn, chưa được mục sư duyệt.</small></div>')
    _h2 = _h.replace('</p><p><small lang="en">', '</p>' + _card + '<p><small lang="en">', 1)
    if _h2 == _h: _h2 = _h.replace("</h1>", "</h1>" + _card, 1)
    open(_p, "w", encoding="utf-8").write(_h2); _n += 1
print("book info cards:", _n)
